ALTER TABLE users ADD COLUMN kyc_status kyc_status DEFAULT 'PENDING';
ALTER TABLE users ADD COLUMN bank_account VARCHAR(50);
ALTER TABLE users ADD COLUMN ifsc VARCHAR(20);
ALTER TABLE users ADD COLUMN pan VARCHAR(20);
ALTER TABLE users ADD COLUMN aadhaar VARCHAR(20);
