ALTER TABLE users DROP COLUMN IF EXISTS kyc_status;
ALTER TABLE users DROP COLUMN IF EXISTS bank_account;
ALTER TABLE users DROP COLUMN IF EXISTS ifsc;
ALTER TABLE users DROP COLUMN IF EXISTS pan;
ALTER TABLE users DROP COLUMN IF EXISTS aadhaar;
